name: Second 
on: push,workflow_dispatch
jobs:
    Install:
        runs-on: ubuntu-latest
        steps:
          - name: Get Code
            uses: actions/checkout@v4
          - name: Install Dependencies
            run: npm ci
    test:
        needs: Install
        runs-on: ubuntu-latest
        steps:
          - name: Get Code
            uses: actions/checkout@v4
          - name: Install Dependencies
            run: npm ci
          - name: Run Lint
            run: npm run lint
          - name: Run Tests
            run: npm run test
    deployment:
        needs: Install, test
        runs-on: ubuntu-latest
        steps:
          - name: Get Code
            uses: actions/checkout@v4
          - name: Install Dependencies
            run: npm ci
          - name: Build
            run: npm run build
          - name: Deploy
            run: echo "Deployment ..."